Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.app.urls', 'app'), namespace='app')),
    path('login/', include(('Core.login.urls', 'login'), namespace='login')),
    path('sold/', include(('Core.solicitud.urls', 'solicitud'), namespace='solicitud')),
    path('solt/', include(('Core.solicitante.urls', 'solicitante'), namespace='solicitante')),
    path('user/', include(('Core.User.urls', 'user'), namespace='user')),
    path('report/', include(('Core.reportes.urls', 'reporte'), namespace='reporte')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/User/urls.py
from django.urls import path

from Core.User.views import *

urlpatterns = [
    path('lista/', UserListView.as_view(), name = 'User_lista'),
    path('add/', UserCreateView.as_view(), name = 'User_crear'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name = 'User_editar'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name = 'User_delete'),
    path('change/group/<int:pk>/', UserChangeGropus.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name = 'User_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='User_change_password'),

]

Core/app/urls.py
from django.urls import path
from .views import*

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

Core/login/urls.py
from django.urls import path
from .views import*
from Core.User.views import *

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password/', ResetPassWordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePassWordView.as_view(), name='change_password'),
]

Core/reportes/urls.py
from django.urls import path

from Core.reportes.views import *

urlpatterns = [ 
    path('sale/', ReportesView.as_view(), name='sale_report'),
    path('misionesygrandesmisiones/', ReportesBaseMisionesView.as_view(), name='reportes_base_Misiones'),
]

templates/vtc/body.html
{% extends "home.html" %}
{% load static %}
{% block body %}
	<body class="hold-transition sidebar-mini layout-fixed">
		<div class="preloader flex-column justify-content-center align-items-center">
			<img class="animation__shake" src="{% static 'img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
		</div>
		<!-- Site wrapper -->
		<div class="wrapper">
			<!-- Navbar -->
			{% include 'vtc/header.html' %}
			<!-- /.navbar -->

			<!-- Main Sidebar Container -->
			{% include 'vtc/sidevar.html' %}
			<!-- /.sidebar -->

			<!-- Content Wrapper. Contains page content -->
			<div class="content-wrapper">
				<!-- Content Header (Page header) -->
				<section class="content-header">
					<div class="container-fluid">
						<div class="row mb-2">
							<div class="col-sm-6">
								<h5 class="m-0 text-dark"> Bienvenido <small> <strong>
									{{ request.user.get_full_name }}
								</strong></small></h5>
							</div>
							<div class="col-sm-6">
								<ol class="breadcrumb float-sm-right">
									<li class="breadcrumb-item"><a href="{% url 'app:dashboard' %}">Home / {{ url }}</a></li> 
								</ol>
							</div>
						</div>
					</div><!-- /.container-fluid -->
				</section>

				{% block content %}
				    
				{% endblock content %}

			</div>
			<!-- /.content-wrapper -->

			{% include 'fooder.html' %}

			<!-- Control Sidebar -->
			<aside class="control-sidebar control-sidebar-dark">
			<!-- Control sidebar content goes here -->
				
			</aside>
		<!-- /.control-sidebar -->

		</div>
		<!-- Block javascript -->
		{% block java %}

		<script>
	        {% if messages %}
	            var html = '<p>';
	            {% for message in messages %}
	                html += '{{ message }}<br>';
	            {% endfor %}
	            html += '</p>';
	            Swal.fire({
	                title: 'Error!',
	                html: html,
	                icon: 'error',
	                timer: 2000,

	                onClose: () => {
	                	location.href = '{{ list_url }}';
	                }
	            });
	            {% endif %}
		</script>

		{% endblock java%}

	</body>
{% endblock body %}
	

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-success">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'app:dashboard' %}" class="nav-link">Home</a>
        </li>
    
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            {% if g.id != request.session.group.id %}
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Último Acceso: {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:User_profile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'user:User_change_password' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login:logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidevar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-success elevation-4">
	<!-- Brand Logo -->
	<a href="{% url 'app:dashboard' %}" class="brand-link">
		<img src="{% static 'img/admin_logo.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
		<span class="brand-text font-weight-light">Ayuda Sociales</span>
	</a>

	<!-- Sidebar -->
	<div class="sidebar">
		<!-- Sidebar user (optional) -->
		<div class="user-panel mt-3 pb-3 mb-3 d-flex">
			<div class="image">
				<img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
			</div>
			<div class="info">
				<a href="#" class="d-block"><h5> <strong>{{user}} </strong></h5></a>
			</div>
		</div>

		<!-- Sidebar Menu -->
		<nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
	      <!-- Add icons to the links using the .nav-icon class
	      	with font-awesome or any other icon font library -->
	      	<li class="nav-item">
	      		<a href="{% url 'app:dashboard' %}" class="nav-link active">
	      			<i class="nav-icon fas fa-tachometer-alt"></i>
	      			<p>DASHBOARD</p>
	      		</a>
	      	</li>

	      	{% if request.user.is_staff %}
	      		
	      	<li class="nav-item">
	      		<a href="{% url 'user:User_lista' %}" class="nav-link active">
	      			<i class="nav-icon fas fa-user"></i>
	      			<p>USUARIOS</p>
	      		</a>
	      	</li>
	      		
	      	<li class="nav-item">
	      		<a href="#" class="nav-link active">
	      			<i class="nav-icon fas fa-users"></i>
	      			<p>
	      				BASE MISIONES
	      				<i class="right fas fa-angle-left"></i>
	      			</p>
	      		</a>
	      		<ul class="nav nav-treeview">
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Add_Base_Misiones' %}" class="nav-link">
	      					<i class="nav-icon fas fa-cash-register"></i>
	      					<p> Registros de Misiones</p>
	      				</a>
	      			</li>
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Lista_Base_Misiones' %}" class="nav-link">
	      					<i class="nav-icon fas fa-clipboard-list"></i>
	      					<p>Listados de Misiones</p>
	      				</a>
	      			</li>
	      		</ul>
	      	</li>
	      	<li class="nav-item">
	      		<a href="#" class="nav-link active">
	      			<i class="nav-icon fas fa-users"></i>
	      			<p>
	      				RESPONSABLES
	      				<i class="right fas fa-angle-left"></i>
	      			</p>
	      		</a>
	      		<ul class="nav nav-treeview">
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Add_Encargados' %}" class="nav-link">
	      					<i class="nav-icon fas fa-cash-register"></i>
	      					<p> Registros de Encargados</p>
	      				</a>
	      			</li>
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Lista_Encargados' %}" class="nav-link">
	      					<i class="nav-icon fas fa-clipboard-list"></i>
	      					<p>Listados de Encargados</p>
	      				</a>
	      			</li>
	      		</ul>
	      	</li>
	      	{% endif %}
    
	      	<li class="nav-item">
	      		<a href="#" class="nav-link active">
	      			<i class="nav-icon fas fa-users"></i>
	      			<p>
	      				SOLICITANTES
	      				<i class="right fas fa-angle-left"></i>
	      			</p>
	      		</a>
	      		<ul class="nav nav-treeview">
	      			<li class="nav-item">
	      				<a href="{% url 'solicitante:Solicitante_Crear' %}" class="nav-link">
	      					<i class="nav-icon fas fa-cash-register"></i>
	      					<p>Registros de Solicitantes</p>
	      				</a>
	      			</li>
	      			<li class="nav-item">
	      				<a href="{% url 'solicitante:Solicitante_Lista' %}" class="nav-link">
	      					<i class="nav-icon fas fa-clipboard-list"></i>
	      					<p>Listados de Solicitantes</p>
	      				</a>
	      			</li>
	      		</ul>
	      	</li>

	      	<li class="nav-item">
	      		<a href="#" class="nav-link active">
	      			<i class="nav-icon fas fa-cogs"></i>
	      			<p>
	      				GESTIONAR
	      				<i class="right fas fa-angle-left"></i>
	      			</p>
	      		</a>
	      		<ul class="nav nav-treeview">
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:base' %}" class="nav-link">
	      					<i class="nav-icon fas fa-hands-helping"></i>
	      					<p>Solicitude</p>
	      				</a>
	      			</li>
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Categorias_lista' %}" class="nav-link">
	      					<i class="nav-icon fas fa-cash-register"></i>
	      					<p>Tipos de Ayuda</p>
	      				</a>
	      			</li>
	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Solicitudes_crear' %}" class="nav-link">
	      					<i class="nav-icon fas fa-cash-register"></i>
	      					<p>Registros de Solicitudes</p>
	      				</a>
	      			</li>

	      			<li class="nav-item">
	      				<a href="{% url 'solicitud:Solicitudes_lista' %}" class="nav-link">
	      					<i class="nav-icon fas fa-clipboard-list"></i>
	      					<p>Listados de Solicitudes</p>
	      				</a>
	      			</li>
	      		</ul>
	      	</li>

	      	{% if request.user.is_staff %}

	      	<li class="nav-item">
	      		<a href="{% url 'reporte:sale_report' %}" class="nav-link active">
	      			<i class="nav-icon fas fa-file-download"></i>
	      			<p>REPORTES</p>
	      		</a>
	      	</li>
	      	<li class="nav-item">
	      		<a href="{% url 'reporte:reportes_base_Misiones' %}" class="nav-link active">
	      			<i class="nav-icon fas fa-file-download"></i>
	      			<p>REPORTES DE MISIONES</p>
	      		</a>
	      	</li>	      
	      	{% endif %}
      	</nav>
      <!-- /.sidebar-menu -->
  	</div>
</aside>