Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.app.urls', 'app'), namespace='app')),
    path('login/', include(('Core.login.urls', 'login'), namespace='login')),
    path('sold/', include(('Core.solicitud.urls', 'solicitud'), namespace='solicitud')),
    path('solt/', include(('Core.solicitante.urls', 'solicitante'), namespace='solicitante')),
    path('user/', include(('Core.User.urls', 'user'), namespace='user')),
    path('report/', include(('Core.reportes.urls', 'reporte'), namespace='reporte')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/User/urls.py
from django.urls import path

from Core.User.views import *

urlpatterns = [
    path('lista/', UserListView.as_view(), name = 'User_lista'),
    path('add/', UserCreateView.as_view(), name = 'User_crear'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name = 'User_editar'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name = 'User_delete'),
    path('change/group/<int:pk>/', UserChangeGropus.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name = 'User_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='User_change_password'),

]

Core/login/urls.py
from django.urls import path
from .views import*
from Core.User.views import *

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password/', ResetPassWordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePassWordView.as_view(), name='change_password'),
]

Core/solicitante/urls.py
from django.urls import path
from Core.solicitante.views.solicitantes.view import*


urlpatterns = [
    # CRUD
    path('lista/', SolicitanteListView.as_view(), name = 'Solicitante_Lista'),
    path('add/', SolicitanteCreateView.as_view(), name = 'Solicitante_Crear'),
    path('update/<int:pk>/', SolicitanteUpdateView.as_view(), name = 'Solicitante_editar'),
    path('delete/<int:pk>/', SolicitanteDeleteView.as_view(), name = 'Solicitante_eliminar'),
    
    ]

Core/solicitud/urls.py
from django.urls import path
from Core.solicitud.views.categorias.view import *
from Core.solicitud.views.solicitud.view import *
from Core.solicitud.views.test.view import *
from Core.solicitud.views.misiones.view import *

urlpatterns = [
    path('solicitudes/', Base.as_view(), name ='base'),
    path('lista/', SolicitudesListView.as_view(), name = 'Solicitudes_lista'),
    path('add/', SolicitudesCreateView.as_view(), name = 'Solicitudes_crear'),
    path('update/<int:pk>/', SolicitudesUpdateView.as_view(), name = 'Solicitudes_editar'),
    path('change/<int:pk>/', SolicitudChangeEstatusView.as_view(), name = 'Solicitudes_Change_estatus'),
    path('delete/<int:pk>/', SolicitudesDeleteView.as_view(), name = 'Solicitudes_eliminar'),
    path('catg/lista/', CategoriasListView.as_view(), name = 'Categorias_lista'),
    path('catg/add/', CategoriasCreateView.as_view(), name = 'Categorias_crear'),
    path('catg/update/<int:pk>/', CategoriasUpdateView.as_view(), name = 'Categorias_editar'),
    path('catg/delete/<int:pk>/', CategoriasDeleteView.as_view(), name = 'Categorias_eliminar'),
    
    # Base de Misiones y Grandes Misones
    path('basemisiones/lista/', BaseMisionesListView.as_view(), name = 'Lista_Base_Misiones'),
    path('basemisiones/add/', BaseMisionesCreateView.as_view(), name = 'Add_Base_Misiones'),
    path('basemisiones/update/<int:pk>/', BaseMisionesUpdateView.as_view(), name = 'Update_Base_Misiones'),
    path('basemisiones/delete/<int:pk>/', BaseMisionesDeleteView.as_view(), name = 'Delete_Base_Misiones'),
    
    # Encargado de Misiones
    path('encargados/lista/', EncargadosListView.as_view(), name = 'Lista_Encargados'),
    path('encargados/add/', EncargadosCreateView.as_view(), name = 'Add_Encargados'),
    path('encargados/update/<int:pk>/', EncargadosUpdateView.as_view(), name = 'Update_Encargados'),
    path('encargados/delete/<int:pk>/', EncargadosDeleteView.as_view(), name = 'Delete_Encargados'),

    # test
    path('test/', TestView.as_view(), name = 'Test_selec2'),
]

templates/hzt/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'hzt/header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1>{{title_body}}</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ url }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'fooder.html' %}
    </div>
    <!-- Block javascript -->
    {% block java %}

    {% endblock %}
    </body>
{% endblock %}

templates/hzt/header.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-success">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'lib/adminLTE-3.2.0/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Adminnistrador</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                {% if request.user.is_staff %}
                    
                    <li class="nav-item">
                        <a href="{% url 'user:User_lista' %}" class="nav-link"><i class="nav-icon fas fa-user"></i> USUARIOS</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="nav-icon fas fa-cogs"></i> GESTIONAR</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'solicitud:Solicitudes_lista' %}" class="dropdown-item"><i class="fas fa-clipboard-list"></i> Listados </a></li>
                        <li><a href="{% url 'solicitud:Solicitudes_crear' %}" class="dropdown-item"><i class="fas fa-cash-register"></i> Registros</a></li>
                        <li><a href="{% url 'solicitud:base' %}" class="dropdown-item"><i class="fas fa-clipboard-list"></i> Solicitud</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-users"></i> SOLICITANTES</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'solicitante:Solicitante_Lista' %}" class="dropdown-item"><i class="fas fa-clipboard-list"></i> Listados </a></li>
                        <li><a href="{% url 'solicitante:Solicitante_Crear' %}" class="dropdown-item"><i class="fas fa-cash-register"></i> Registros</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            {% if request.user.groups.all %}
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}<i class="fas fa-users"></i> Perfil </a>
                    {% if request.user.groups.all.count > 1 %}
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                            style="left: 0px; right: inherit;">
                            {% for g in request.user.groups.all %}
                                {% if g.id != request.session.group.id %}
                                    <li><a href="#"
                                           class="dropdown-item">{{ g.name }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-users-cog"> {{ request.user.username }}</i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Último Acceso: {{ request.user.last_login }}
                    </span>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:User_profile' %}" class="dropdown-item">
                        <i class="fas fa-edit mr-2"></i> Editar perfil
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:User_change_password' %}" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>Este sistema te permitira realizar diferentes actividades</p>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login:logout' %}">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>