Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.app.urls', 'app'), namespace='app')),
    path('login/', include(('Core.login.urls', 'login'), namespace='login')),
    path('sold/', include(('Core.solicitud.urls', 'solicitud'), namespace='solicitud')),
    path('solt/', include(('Core.solicitante.urls', 'solicitante'), namespace='solicitante')),
    path('user/', include(('Core.User.urls', 'user'), namespace='user')),
    path('report/', include(('Core.reportes.urls', 'reporte'), namespace='reporte')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/app/urls.py
from django.urls import path
from .views import*

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

Core/login/urls.py
from django.urls import path
from .views import*
from Core.User.views import *

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset/password/', ResetPassWordView.as_view(), name='reset_password'),
    path('change/password/<str:token>/', ChangePassWordView.as_view(), name='change_password'),
]

Core/login/models.py
from django.db import models

# Create your models here.

Core/login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from Core.User.models import User

""" Formularios de Login """


class ResetPassWordForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(
			attrs={
				'placeholder': 'Ingrese un usuario',
				'class': 'form-control',
				'autocomplete': 'off'
		}))

	def clean(self):
		cleaned = super().clean()

		if not User.objects.filter(username=cleaned['username']).exists():
			self._errors['error'] = self._errors.get('error', self.error_class())
			self._errors['error'].append('El usuario no exixte')
			#raise forms.ValidationError('El usuario no existe')
		
		return cleaned		


	def get_user(self):
		username = self.cleaned_data.get('username')
		return User.objects.get(username=username)




class ChangedPassWordForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'Ingrese una contraseña',
		'class': 'form-control',
		'autocomplete': 'off'
		}))

	confirmarPassword = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder': 'repita la contraseña',
		'class': 'form-control',
		'autocomplete': 'off'
		}))

	def clean(self):
		cleaned = super().clean()
		password = cleaned['password']
		confirmarPassword = cleaned['confirmarPassword']

		if password != confirmarPassword:
			self._errors['error'] = self._errors.get('error', self.error_class())
			self._errors['error'].append('Las contraseñas deben ser iguales')

			#raise forms.ValidationError('las contraseñas deben ser iguales')
	
		return cleaned

Core/login/views.py
import smtplib
import uuid

from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import *
import Config.settings as settings

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from Config.wsgi import*
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.template.loader import render_to_string

from Core.User.models import *

from .forms import *
# Create your views here.


class LoginFormView(FormView):
	form_class = AuthenticationForm
	template_name = 'login/Login.html'
	success_url = reverse_lazy('app:dashboard')

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return HttpResponseRedirect(self.success_url)
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		login(self.request, form.get_user())
		return HttpResponseRedirect(self.success_url)


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Iniciar Sesion'
		return context



class ResetPassWordView(FormView):
	form_class = ResetPassWordForm
	template_name = 'login/resetpwd.html'
	success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		return super().dispatch(request, *args, **kwargs)


	def send_email_reset_pwd(self, User):
		data = {}
		try:
			URL= settings.DOMAIN if not settings.DEBUG else self.request.META['HTTP_HOST']


			User.token = uuid.uuid4()
			User.save()

			mailServer = smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT)
			mailServer.starttls()
			mailServer.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

        	# Construimos el mensaje simple
        	# Plantilla optenida de beefree.io

			email_to = User.email
			mensaje = MIMEMultipart()
			mensaje['From'] = settings.EMAIL_HOST_USER
			mensaje['To'] = email_to
			mensaje['Subject'] = "reseteo de contraseña"

			content = render_to_string('login/send_email.html', {
				'user': User, 
				'link_resetpwd': 'http://{}/login/change/password/{}/'.format(URL, str(User.token)),
				'link_home': 'http://{}'.format(URL)

        	})
			mensaje.attach(MIMEText(content, 'html'))

			mailServer.sendmail(settings.EMAIL_HOST_USER,
		                    email_to,
		                    mensaje.as_string())

		except Exception as e:
			data['error'] = str(e)
		
		return data

	

	def post(self, request, *args, **kwargs):
		data = {}
		try:
			form = ResetPassWordForm(request.POST)  # es lo mismo que utilizar == self.get_form
			print(request.POST)
			if form.is_valid():
			    user = form.get_user()
			    data = self.send_email_reset_pwd(user)
			else:
				data['error'] = form.errors
		except Exception as e:
		    data['error'] = str(e)
		return JsonResponse(data, safe=False)



	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Reseteo de Contraseña'
		return context



class ChangePassWordView(FormView):
	form_class = ChangedPassWordForm
	template_name = 'login/Changepwd.html'
	success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)


	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		return super().dispatch(request, *args, **kwargs)


	def get(self, request, *args, **kwargs):
		token = self.kwargs['token']
		if User.objects.filter(token=token).exists():
			return super().get(request, *args, **kwargs)
		return HttpResponseRedirect(settings.LOGIN_URL)


	def post(self, request, *args, **kwargs):
		data = {}
		try:
			form = ChangedPassWordForm(request.POST)
			if form.is_valid():
				user = User.objects.get(token=self.kwargs['token'])
				user.set_password(request.POST['password'])
				user.token = uuid.uuid4()
				user.save()
			else:
				data['error'] = form.errors

		except Exception as e:
			data['error'] = str(e)
		return JsonResponse(data, safe=False)

	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Recuperar Contraseña'
		context['login_url'] = settings.LOGIN_URL
		return context

Core/login/templates/login/Changepwd.html
{% extends 'login/Login.html'%}
{% load static %}
{% block content%}
	<div class="login-box">
		<div class="login-logo">
			<a href="{% url 'app:index' %}" class="h1"><b>SAGS</b>Portuguesa</a>
		</div>
		<div class="card card-outline card-success">
			<div class="card-body">
				<p class="login-box-msg">Cambio de contraseña</p>
				<form action="#" method="post">
		  			<input type="hidden" name="next" value=" {{ next }} " >
		  			{% csrf_token %}
			   		<div class="input-group mb-3">
						{{ form.password }}
			      		<div class="input-group-append">
			        		<div class="input-group-text">
			         			<span class="fas fa-lock"></span>
			        		</div>
			      		</div>
		    		</div>
		    		<div class="input-group mb-3">
						{{ form.confirmarPassword }}
			      		<div class="input-group-append">
			        		<div class="input-group-text">
			         			<span class="fas fa-lock"></span>
			        		</div>
			      		</div>
		    		</div>
			    	<div class="row">
			    		<div class="col-12">
			    			<button type="submit" class="btn btn-success btn-block">
			    				<i class="fa fa-paper-plane" aria-hidden="true"></i> Cambiar contraseña
			    			</button>
			    		</div>
			    	</div>
			    </form>
			    <p class="mt-3 mb-1">
			    	<a href="{{ login_url }}"> Login</a>
			    </p>
			</div>
		</div>
    </div>
    <script type="application/javascript">
		$(function () {
			$('form').on('submit', function (e) {
				e.preventDefault();
				//var parameters = new FormData(this);

				var parameters = $(this).serializeArray();

				submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de cambiar tu contraseña?', parameters,function () {
						Swal.fire({
							title: 'Notificación',
							text: 'Tu contraseña ha sido cambiada exitoxamente',
							icon: 'success',
							timer: 5000,
							onClose: () => {
								location.href = '{{ login_url }}' ;
							}
						}).then((result) => {

						})
				});
			});
		});
	</script>  
{% endblock %}

Core/login/templates/login/Login.html
{% extends 'login/Login.html'%}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="login-box">

        <div class="card-header text-center">
            <a href="{% url 'app:index' %}" class="h1"><b>SAGS</b>Portuguesa</a>
        </div>
        <div class="card card-outline card-success">
            <div class="card-body">
                <img src="{% static 'img/SDHC.png' %} " width="300" height="200">
                <p class="login-box-msg">Iniciar tu sesión</p>
                <form action="#" method="post">
                {% csrf_token %}
                    <input type="hidden" name="next" value=" {{next}} " >
                    <div class="input-group mb-3">
                    <input type="text" class="form-control form-control-user" id="id_username" name="username" placeholder="Username">
                        <div class="input-group-append">
                        <div class="input-group-text">
                        <span class="fas fa-user"></span>
                        </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" id="id_password" name="password" class="form-control form-control-user"  placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success btn-block"><span class="fas fa-sign-in-alt"></span> Acceder</button>
                        </div>
                        <div class="col-lg-12">
                            <p class="mt-4 mb-0">
                                <a href="{% url 'login:reset_password' %}"> Olvidé mi contraseña</a>
                            </p>
                        </div>
                    
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="application/javascript">
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
    </script>
{% endblock content %}

Core/login/templates/login/resetpwd.html
{% extends 'login/Login.html'%}
{% load static %}

{% block content %}

	<div class="login-box">
		<div class="login-logo">
			<a href="{% url 'app:index' %}" class="h1"><b>SAGS</b>Portuguesa</a>
		</div>
		<div class="card card-outline card-success">
			<div class="card-body">
				<p class="login-box-msg" style="font-size:15px;">Olvidaste tu contraseña? Aquí puede recuperar fácilmente una nueva contraseña.</p>
				<form action="#" method="post">
		  			<input type="hidden" name="next" value=" {{next}} " >
		  			{% csrf_token %}
			   		<div class="input-group mb-3">
						{{ form.username }}
			      		<div class="input-group-append">
			        		<div class="input-group-text">
			         			<span class="fas fa-envelope"></span>
			        		</div>
			      		</div>
		    		</div>
			    	<div class="row">
			    		<div class="col-12">
			    			<button type="submit" class="btn btn-success btn-block">
			    				<i class="fa fa-paper-plane" aria-hidden="true"></i> Nueva contraseña
			    			</button>
			    		</div>
			    	</div>
			    </form>
			    <p class="mt-3 mb-1">
			    	<a href="{% url 'login:login' %}"> Login</a>
			    </p>
			</div>
		</div>

    </div>
	<script type="application/javascript">
		$(function () {
			$('form').on('submit', function (e) {
				e.preventDefault();
				//var parameters = new FormData(this);

				var parameters = $(this).serializeArray();

				submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de resetear tu contraseña?', parameters,function () {
						Swal.fire({
							title: 'Notificación',
							text: 'Se ha enviado un correo electrónico con los pasos a seguir para que pueda resetear su contraseña',
							icon: 'success',
							timer: 5000,
							onClose: () => {
								location.href = '{{ login_url }}' ;
							}
						}).then((result) => {

						})
				});
			});
		});
	</script>  
	
{% endblock %}