Config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Core.app.urls', 'app'), namespace='app')),
    path('login/', include(('Core.login.urls', 'login'), namespace='login')),
    path('sold/', include(('Core.solicitud.urls', 'solicitud'), namespace='solicitud')),
    path('solt/', include(('Core.solicitante.urls', 'solicitante'), namespace='solicitante')),
    path('user/', include(('Core.User.urls', 'user'), namespace='user')),
    path('report/', include(('Core.reportes.urls', 'reporte'), namespace='reporte')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/solicitante/urls.py
from django.urls import path
from Core.solicitante.views.solicitantes.view import*


urlpatterns = [
    # CRUD
    path('lista/', SolicitanteListView.as_view(), name = 'Solicitante_Lista'),
    path('add/', SolicitanteCreateView.as_view(), name = 'Solicitante_Crear'),
    path('update/<int:pk>/', SolicitanteUpdateView.as_view(), name = 'Solicitante_editar'),
    path('delete/<int:pk>/', SolicitanteDeleteView.as_view(), name = 'Solicitante_eliminar'),
    
    ]

Core/solicitud/urls.py
from django.urls import path
from Core.solicitud.views.categorias.view import *
from Core.solicitud.views.solicitud.view import *
from Core.solicitud.views.test.view import *
from Core.solicitud.views.misiones.view import *

urlpatterns = [
    path('solicitudes/', Base.as_view(), name ='base'),
    path('lista/', SolicitudesListView.as_view(), name = 'Solicitudes_lista'),
    path('add/', SolicitudesCreateView.as_view(), name = 'Solicitudes_crear'),
    path('update/<int:pk>/', SolicitudesUpdateView.as_view(), name = 'Solicitudes_editar'),
    path('change/<int:pk>/', SolicitudChangeEstatusView.as_view(), name = 'Solicitudes_Change_estatus'),
    path('delete/<int:pk>/', SolicitudesDeleteView.as_view(), name = 'Solicitudes_eliminar'),
    path('catg/lista/', CategoriasListView.as_view(), name = 'Categorias_lista'),
    path('catg/add/', CategoriasCreateView.as_view(), name = 'Categorias_crear'),
    path('catg/update/<int:pk>/', CategoriasUpdateView.as_view(), name = 'Categorias_editar'),
    path('catg/delete/<int:pk>/', CategoriasDeleteView.as_view(), name = 'Categorias_eliminar'),
    
    # Base de Misiones y Grandes Misones
    path('basemisiones/lista/', BaseMisionesListView.as_view(), name = 'Lista_Base_Misiones'),
    path('basemisiones/add/', BaseMisionesCreateView.as_view(), name = 'Add_Base_Misiones'),
    path('basemisiones/update/<int:pk>/', BaseMisionesUpdateView.as_view(), name = 'Update_Base_Misiones'),
    path('basemisiones/delete/<int:pk>/', BaseMisionesDeleteView.as_view(), name = 'Delete_Base_Misiones'),
    
    # Encargado de Misiones
    path('encargados/lista/', EncargadosListView.as_view(), name = 'Lista_Encargados'),
    path('encargados/add/', EncargadosCreateView.as_view(), name = 'Add_Encargados'),
    path('encargados/update/<int:pk>/', EncargadosUpdateView.as_view(), name = 'Update_Encargados'),
    path('encargados/delete/<int:pk>/', EncargadosDeleteView.as_view(), name = 'Delete_Encargados'),

    # test
    path('test/', TestView.as_view(), name = 'Test_selec2'),
]

Core/solicitud/models.py
from django.db import models
from datetime import datetime
from crum import get_current_user

from django.forms import model_to_dict

from Core.solicitante.models import Solicitante
from Core.solicitud.choices import *

from django.conf import settings
# Create your models here.


class BaseModel(models.Model):
	user_creation = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_creation', null=True, blank=True)
	date_creation = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	user_update = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_update', null=True, blank=True)
	date_updated = models.DateTimeField(auto_now=True, null=True, blank=True)

	class Meta:
		verbose_name = "Basemodel"
		verbose_name_plural = "basemodels"
		db_table = 'user'

class Categorias(BaseModel):
	nombre = models.CharField(max_length=25, verbose_name='Nombre', unique=True)
	descipcion = models.CharField(max_length=250, null=False, blank=False, verbose_name='Descripcion')

	class Meta:
		verbose_name = "Categorias"
		verbose_name_plural = "Categorias"
		db_table = 'Categoria_Solicitud'

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		user = get_current_user()
		if user is not None:
			if not self.pk:
				self.user_creation = user
			else:
				self.user_update = user
			super(Categorias, self).save()
	
	def toJSON(self):
		item = model_to_dict(self)
		return item

	def __str__(self):
		return str(self.nombre)


class Solicitudes(models.Model):
	fecha_registro = models.DateField(auto_now_add=True)
	categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE, verbose_name='Categoria')
	id_solicitante = models.ForeignKey(Solicitante, on_delete=models.CASCADE, verbose_name= 'Solicitante')
	estatus = models.CharField(max_length=9, choices=aprobado_choices, default='ESPERA',null=True, blank=True, verbose_name='Estatus')
	descripcion = models.CharField(max_length=250, null=False, blank=False, verbose_name='Descripcion')
	descripcion_motivo = models.CharField(max_length=250, null=True, blank=True, verbose_name='Descripcion')


	def toJSON(self):
		item = model_to_dict(self)
		item['fecha_registro'] = self.fecha_registro.strftime('%Y-%m-%d')
		item['categoria'] = self.categoria.toJSON()
		item['id_solicitante'] = self.id_solicitante.toJSON()
		return item

	def __str__(self):
		return '{} {} {}'.format(self.id, self.id_solicitante, self.estatus)





class EncargadoBaseMisiones(models.Model):
	cedula = models.CharField(max_length=10, unique=True, verbose_name='Cedula')
	fecha_nacimiento = models.DateField(auto_now=False, auto_now_add=False, verbose_name='Fecha de nacimiento')
	nombre = models.CharField(max_length=50, null=False, blank=False, verbose_name='Nombres')
	apellido = models.CharField(max_length=50, null=False, blank=False, verbose_name='Apellidos')
	edad = models.IntegerField()
	sexo = models.CharField(max_length=10, choices=sexo, default='M',null=False, blank=False, verbose_name='Sexo')
	email = models.EmailField(unique=True)
	telefono = models.CharField(max_length=30, null=False, blank=False, verbose_name='Telefono')
	codigo = models.CharField(max_length=9, unique=True, blank=False, null=False, verbose_name='Codigo')
	serial = models.CharField(max_length=9, unique=True, blank=False, null=False, verbose_name='Serial')

	def __str__(self):
		return self.get_full_name()

	def get_full_name(self):
		return '{} / {} {}'.format(self.cedula, self.apellido, self.nombre)


	def toJSON(self):
		item = model_to_dict(self)
		item['full_name'] = self.get_full_name()
		item['full_person'] = '{} / {} / {}'.format(self.fecha_nacimiento.strftime('%Y-%m-%d'), self.edad, self.sexo)
		item['full_contact'] = '{} / {}'.format(self.telefono, self.email)
		item['datos_patria'] = '{} / {}'.format(self.codigo, self.serial)
		return item



	class Meta:
		verbose_name = 'Encargado'
		verbose_name_plural = 'Encargados'
		db_table='Encargados'
		ordering = ['id']




class BaseGrandesMisiones(models.Model):
	nombre = models.CharField(max_length=25, verbose_name='Nombre de la Base de Misiones', unique=True)
	responsable = models.ForeignKey(EncargadoBaseMisiones, on_delete=models.CASCADE, verbose_name='Encargado o Responsable')
	municipio = models.CharField(max_length=100, choices=municipios, default='GUANARE',null=False, blank=False, verbose_name='Municipios')
	nombre_p = models.CharField(max_length=50, null=False, blank=False, verbose_name='Nombre de la Parroquia')
	nombre_c = models.CharField(max_length=50, null=False, blank=False, verbose_name='Nombre de la Comunidad')


	def __str__(self):
		return self.nombre


	def toJSON(self):
		item = model_to_dict(self)
		item['responsable'] = self.responsable.toJSON()
		return item

	class Meta:
		verbose_name = 'Base_de_Misiones_y_Grandes_Misiones'
		verbose_name_plural = 'Base_de_Misiones_y_Grandes_Misiones'
		db_table='Misiones_y_Grandes_Misiones'
		ordering = ['id']

Core/solicitud/forms.py
from datetime import datetime

from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from .models import *

class CategoriasForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('nombre', css_class='form-group col-md-6'),
				Column('descipcion', css_class='form-group col-md-6'),
				css_class='form-row'
				),
			)

	class Meta:
		model = Categorias
		fields = '__all__'
		widgets = {
		'nombre':forms.TextInput(attrs={'class':'form-control','placeholder':'Introduce tipo de ayuda'}),
		'descipcion':forms.TextInput(attrs={'class':'form-control','placeholder':'Introduce descripcion de ayuda'}),
		}
		exclude =['user_creation','user_update']


	def save(self):
		data = {}
		form = super()
		try:
			if form.is_valid():
				form.save()
			else:
				data['error'] = form.errors
		except Exception as e:
			data['error'] = str(e)
		return data



class SolicitudesForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('categoria', css_class='form-group col-md-6'),
				Column('id_solicitante', css_class='form-group col-md-6'),
				Column('descripcion', css_class='form-group col-md-12'),
				css_class='form-row'
				),
			)

	class Meta:
		model = Solicitudes
		fields = '__all__'
		widgets = {
			'categoria':forms.Select(attrs={'class':'form-control select2 mt-3'}),
			'id_solicitante':forms.Select(attrs={'class':'form-control select2 mt-3'}),
			'descripcion':forms.Textarea(attrs={'class':'form-control mt-3','rows': 3, 'cols': 3}),
		}
		exclude =['user_creation','user_update']
	def save(self):
		data = {}
		form = super()
		try:
			if form.is_valid():
				form.save()
			else:
				data['error'] = form.errors
		except Exception as e:
			data['error'] = str(e)
		return data



class SolicitudesForm2(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('estatus', css_class='form-group col-md-12'),
				Column('descripcion_motivo', css_class='form-group col-md-12'),
				css_class='form-row'
				),
			)

	class Meta:
		model = Solicitudes
		fields = '__all__'
		widgets = {
			'estatus':forms.Select(attrs={'class':'form-control select2 mt-3'}),
			'descripcion_motivo':forms.Textarea(attrs={'class':'form-control mt-3','rows': 3, 'cols': 3}),
		}
		exclude =['id_solicitante','categoria','descripcion','user_creation','user_update']
	def save(self):
		data = {}
		form = super()
		try:
			if form.is_valid():
				form.save()
			else:
				data['error'] = form.errors
		except Exception as e:
			data['error'] = str(e)
		return data




class TestForm(forms.Form):
    categories = forms.ModelChoiceField(queryset=Categorias.objects.all(), widget=forms.Select(attrs={
        'class': 'form-control select2',
        'style': 'width: 100%'
    }))

    products = forms.ModelChoiceField(queryset=Solicitudes.objects.none(), widget=forms.Select(attrs={
        'class': 'form-control select2',
        'style': 'width: 100%'
    }))

    # search = CharField(widget=TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'Ingrese una descripción'
    # }))

    search = forms.ModelChoiceField(queryset=Solicitudes.objects.none(), widget=forms.Select(attrs={
        'class': 'form-control select2',
        'style': 'width: 100%'
    }))


class EncargadoForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('cedula', css_class='form-group col-md-4'),
				Column('nombre', css_class='form-group col-md-4'),
				Column('apellido', css_class='form-group col-md-4'),
				Column('fecha_nacimiento', css_class='form-group col-md-4'),
				Column('edad', css_class='form-group col-md-4'),
				Column('sexo', css_class='form-group col-md-4'),
				Column('codigo', css_class='form-group col-md-6'),
				Column('serial', css_class='form-group col-md-6'),
				Column('telefono', css_class='form-group col-md-12'),
				Column('email', css_class='form-group col-md-12'),
				css_class='form-row'
				),
			)

	class Meta:
		model = EncargadoBaseMisiones
		fields = 'cedula', 'nombre', 'apellido','fecha_nacimiento','edad','sexo','telefono','email','codigo', 'serial'
		widgets = {
	        'cedula':forms.TextInput(
	        	attrs = {
	        		'class': 'form-control',
	        		'placeholder':'Introduce tus numero de Cedula'
	        	}),

            'nombre':forms.TextInput(
            	attrs={
            		'class':'form-control',
            		'placeholder':'Introduce tus Nombres'
            	}),

	        'apellido':forms.TextInput(
	        	attrs = {
	        		'class': 'form-control',
	        		'placeholder':'Introduce tus Apellidos'
	        	}),


	        'fecha_nacimiento':forms.DateTimeInput(
	        	attrs = {
	        		'class': 'form-control',
	        		'type':'date',
	        	}),

	        'edad':forms.NumberInput(
	        	attrs = {
	        		'class': 'form-control',
	        		
	        	}),

	        'sexo':forms.Select(
	        	attrs = {
	        		'class': 'form-control select2',
	        		
	        	}),

	        'telefono':forms.TextInput(
	        	attrs = {
	        		'class': 'form-control',
	        		'placeholder':'Telefono fijo o de Casa'
	        	}),

	        'email':forms.EmailInput(
	        	attrs = {
	        		'class': 'form-control',
	        		'placeholder':'Introduce correo electronico'
	        	}),

	        'codigo':forms.NumberInput(
	        	attrs = {
	        	'class': 'form-control',
	        	'placeholder':'Codigo de carnet de la Patria',
	        	'id':'id_codigo'
	        	}),

	        'serial':forms.NumberInput(
	        	attrs = {
	        	'class': 'form-control',
	        	'placeholder':'Serial de carnet de la Patria',
	        	'id':'id_codigo'
	        	}),
        }

	def save(self):
		data = {}
		form = super()
		try:
			if form.is_valid():
				form.save()
			else:
				data['error'] = form.errors
		except Exception as e:
			data['error'] = str(e)
		return data




class BaseMisionesGrandeMisionesForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.layout = Layout(
			Row(
				Column('nombre', css_class='form-group col-md-4'),
				Column('responsable', css_class='form-group col-md-8'),
				Column('municipio', css_class='form-group col-md-4'),
				Column('nombre_p', css_class='form-group col-md-4'),
				Column('nombre_c', css_class='form-group col-md-4'),
				css_class='form-row'
				),
			)

	class Meta:
		model = BaseGrandesMisiones
		fields = 'nombre','responsable','municipio','nombre_p','nombre_c'
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'responsable':forms.Select(attrs={'class':'form-control select2'}),
			'municipio':forms.Select(attrs={'class':'form-control select2'}),
			'nombre_p':forms.TextInput(attrs={'class':'form-control'}),
			'nombre_c':forms.TextInput(attrs={'class':'form-control'}),
		}
	def save(self):
		data = {}
		form = super()
		try:
			if form.is_valid():
				form.save()
			else:
				data['error'] = form.errors
		except Exception as e:
			data['error'] = str(e)
		return data

Core/solicitud/templates/solicitud/Change_estatus.html
{% extends "form.html" %}

Core/solicitud/templates/solicitud/Lista_Solicitudes.html
{% extends "list.html" %}
{% load static %}

{% block head_list %}

	<script src="{% static 'solicitud/js/list.js' %}"></script>

{% endblock head_list %}

{% block columns %}
	<tr>
		<th scope="col" style="width: 10%;">ID</th>
		<th scope="col" style="width: 10%;">CATEGORIA</th>
		<th scope="col" style="width: 20%;">SOLICITANTE</th>
		<th scope="col" style="width: 10%;">FECHA REGISTRO</th>
		<th scope="col" style="width: 20%;">ESTATUS</th>
		<th scope="col" style="width: 10%;">DESCRIPCION</th>
		<th scope="col" style="width: 10%;">DESCRIPCION MOTIVO</th>
		<th scope="col" style="width: 10%;">OPCIONES</th>
	</tr>

{% endblock columns %}

{% block rows %}

{% endblock rows %}

{% block java %}

{% endblock java%}

Core/solicitud/templates/solicitud/Solicitudes_Delete.html
{% extends "delete.html" %}

Core/solicitud/templates/solicitud/Solicitudes_Form.html
{% extends "form.html" %}

Core/solicitud/templates/solicitud/base.html
{% extends "layout.html" %}
{% load static %}
{% block head %}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock head %}

{% block content %}
    <style type="text/css">
        .highcharts-figure,
        .highcharts-data-table table {
            min-width: 310px;
            max-width: 800px;
            margin: 1em auto;
        }

        #container {
            height: 400px;
        }

        .highcharts-data-table table {
            font-family: Verdana, sans-serif;
            border-collapse: collapse;
            border: 1px solid #ebebeb;
            margin: 10px auto;
            text-align: center;
            width: 100%;
            max-width: 500px;
        }

        .highcharts-data-table caption {
            padding: 1em 0;
            font-size: 1.2em;
            color: #555;
        }

        .highcharts-data-table th {
            font-weight: 600;
            padding: 0.5em;
        }

        .highcharts-data-table td,
        .highcharts-data-table th,
        .highcharts-data-table caption {
            padding: 0.5em;
        }

        .highcharts-data-table thead tr,
        .highcharts-data-table tr:nth-child(even) {
            background: #f8f8f8;
        }

        .highcharts-data-table tr:hover {
            background: #f1f7ff;
        }
        .highcharts-figure,
        .highcharts-data-table table {
            min-width: 310px;
            max-width: 800px;
            margin: 1em auto;
        }

        #container {
            height: 400px;
        }

        .highcharts-data-table table {
            font-family: Verdana, sans-serif;
            border-collapse: collapse;
            border: 1px solid #ebebeb;
            margin: 10px auto;
            text-align: center;
            width: 100%;
            max-width: 500px;
        }

        .highcharts-data-table caption {
            padding: 1em 0;
            font-size: 1.2em;
            color: #555;
        }

        .highcharts-data-table th {
            font-weight: 600;
            padding: 0.5em;
        }

        .highcharts-data-table td,
        .highcharts-data-table th,
        .highcharts-data-table caption {
            padding: 0.5em;
        }

        .highcharts-data-table thead tr,
        .highcharts-data-table tr:nth-child(even) {
            background: #f8f8f8;
        }

        .highcharts-data-table tr:hover {
            background: #f1f7ff;
        }
        .highcharts-figure,
        .highcharts-data-table table {
            min-width: 310px;
            max-width: 800px;
            margin: 1em auto;
        }

        #container {
            height: 400px;
        }

        .highcharts-data-table table {
            font-family: Verdana, sans-serif;
            border-collapse: collapse;
            border: 1px solid #ebebeb;
            margin: 10px auto;
            text-align: center;
            width: 100%;
            max-width: 500px;
        }

        .highcharts-data-table caption {
            padding: 1em 0;
            font-size: 1.2em;
            color: #555;
        }

        .highcharts-data-table th {
            font-weight: 600;
            padding: 0.5em;
        }

        .highcharts-data-table td,
        .highcharts-data-table th,
        .highcharts-data-table caption {
            padding: 0.5em;
        }

        .highcharts-data-table thead tr,
        .highcharts-data-table tr:nth-child(even) {
            background: #f8f8f8;
        }

        .highcharts-data-table tr:hover {
            background: #f1f7ff;
        }

    </style>

	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-12">
				<!-- small box -->
				<a href="{% url 'solicitud:Categorias_lista' %}" class="card card-primary callout callout-success small-box bg-white">
					<div class="inner">
						<h3>Tipos de Ayuda</h3>
					</div>
					<div class="icon">
						<i class="ion ion-bag"></i>
					</div>
				</a>
			</div>
            <div class="col-lg-12 col-12 ">
                <!-- small card -->
                <a class="small-box bg-white callout callout-success mb-4" href='{% url "solicitud:Solicitudes_lista" %}'>
                    <div class="inner">
                        <h3>Lista de Solicitudes</h3>
                        <p>La Solicitud de ayuda se conforman por una categoria y un solicitante.</p>

                    </div>
                    <div class="icon">
                        <i class="fas fa-edit"></i>
                    </div>
                </a>
            </div>
            <div class="col-lg-12 col-12 ">
                <!-- small card -->
                <a class="small-box bg-white callout callout-success mb-4" href='{% url "solicitud:Solicitudes_crear" %}'>
                    <div class="inner">
                        <h3>Crear una Solicitud</h3>
                        <p></p>

                    </div>
                    <div class="icon">
                        <i class="fas fa-plus"></i>
                    </div>
                </a>
            </div>
                        <!-- ./col -->
            <div class="col-lg-12 col-12">
                <!-- small card -->
                <a href="{% url 'solicitante:Solicitante_Lista' %}" class="small-box bg-white callout callout-success mb-4">
                    <div class="inner">
                        <h3>Lista de Solicitantes</h3>

                        <p>Solicitantes</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-list"></i>
                    </div>
                </a>
            </div>
                        <!-- ./col -->
            <div class="col-lg-12 col-12">
                <!-- small card -->
                <a href="{% url 'solicitante:Solicitante_Lista' %}" class="small-box bg-white callout callout-success mb-4">
                    <div class="inner">
                        <h3>Registrar nuevo Solicitantes</h3>

                        <p>Solicitantes</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-user-plus"></i>
                    </div>
                </a>
            </div>
		</div>
	</div>

{% endblock content %}

Core/solicitud/templates/solicitud/test.html
{% extends 'layout.html' %}

{% load static %}
{% block head %}
    <link href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>

    <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="container-fluid">
            <div class="card card-success card-outline">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-plus"></i>
                        {{ title }}
                    </h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label>Categorias:</label>
                        {{ form.categories }}
                    </div>
                    <div class="form-group">
                        <label>Productos:</label>
                        {{ form.products }}
                    </div>
                    <div class="form-group">
                        <label>Buscador:</label>
                        {{ form.search }}
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script>
        var select_products = $('select[name="products"]');
        $(function () {

            $('.select2').select2({
                theme: "bootstrap4",
                language: 'es'
            });

            $('select[name="categories"]').on('change', function () {
                var id = $(this).val();
                var options = '<option value="">--------------------</option>';
                if (id === '') {
                    select_products.html(options);
                    return false;
                }
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {
                        'action': 'search_product_id',
                        'id': id
                    },
                    dataType: 'json',
                }).done(function (data) {
                    if (!data.hasOwnProperty('error')) {
                        select_products.html('').select2({
                            theme: "bootstrap4",
                            language: 'es',
                            data: data
                        });
                        /*$.each(data, function (key, value) {
                            options += '<option value="' + value.id + '">' + value.name + '</option>';
                        });*/
                        return false;
                    }
                    message_error(data.error);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {
                    //select_products.html(options);
                });
            });

            select_products.on('change', function () {
                var value = select_products.select2('data')[0];
                console.log(value);
            });

            var availableTags = [
                "ActionScript",
                "AppleScript",
                "Asp",
                "BASIC",
                "C",
                "C++",
                "Clojure",
                "COBOL",
                "ColdFusion",
                "Erlang",
                "Fortran",
                "Groovy",
                "Haskell",
                "Java",
                "JavaScript",
                "Lisp",
                "Perl",
                "PHP",
                "Python",
                "Ruby",
                "Scala",
                "Scheme"
            ];

            $('input[name="search"]').autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: window.location.pathname,
                        type: 'POST',
                        data: {
                            'action': 'autocomplete',
                            'term': request.term
                        },
                        dataType: 'json',
                    }).done(function (data) {
                        response(data);
                    }).fail(function (jqXHR, textStatus, errorThrown) {
                        //alert(textStatus + ': ' + errorThrown);
                    }).always(function (data) {

                    });
                },
                delay: 500,
                minLength: 1,
                select: function (event, ui) {
                    console.log(ui.item);
                }
            });

            $('select[name="search"]').select2({
                theme: "bootstrap4",
                language: 'es',
                allowClear: true,
                ajax: {
                    delay: 250,
                    type: 'POST',
                    url: window.location.pathname,
                    data: function (params) {
                        var queryParameters = {
                            term: params.term,
                            action: 'autocomplete'
                        }
                        return queryParameters;
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                },
                placeholder: 'Ingrese una descripción',
                minimumInputLength: 1,
            });
        });
    </script>
{% endblock %}